--- 
- hosts: localhost

  vars:
    ami: ami-e60e5a89
    aws_access_key: AKIAIUJF5JEO5U35TMMA
    aws_region: ap-southeast-1
    aws_secret_key: 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
    instance_type: t2.micro
    keypair: docker
    public_subnet_cidr: 10.10.10.0/24
    vpc_cidr_block: 10.10.0.0/16
    vpc_name: "My VPC"

  tasks: 
    - name: "Create VPC"
      ec2_vpc_net: 
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_cidr_block }}"
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        state: present
      register: my_vpc
     
    - name: "set fact VPC ID"
      set_fact: 
        vpc_id: "{{ my_vpc.vpc.id }}"
    - name: "Create Public Subnet"
      ec2_vpc_subnet: 
        state: present
        vpc_id: "{{ vpc_id }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        az: "{{ aws_region }}a"
        cidr: "{{ public_subnet_cidr }}"
        region: "{{ aws_region }}"
        resource_tags: 
          Name: "Public Subnet"
      register: my_public_subnet
    
    - name: "Set Public Subnet ID in variable"
      set_fact: 
        public_subnet_id: "{{ my_public_subnet.subnet.id }}"
    - name: "Create Internet Gateway for VPC"
      ec2_vpc_igw: 
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ aws_region }}"
        state: present
        vpc_id: "{{ vpc_id }}"
      register: my_vpc_igw
      
    - name: "Set Internet Gateway ID in a variable"
      set_fact: 
        igw_id: "{{ my_vpc_igw.gateway_id }}"
    - name: "Set up public subnet route table"
      ec2_vpc_route_table: 
        vpc_id: "{{ vpc_id }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ aws_region }}"
        routes:  
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_id }}"
        subnets: 
          - "{{ public_subnet_id }}"
        tags: 
          Name: Public
        
    - name: "Create Main Security Group"
      ec2_group: 
        name: "My Security Group"
        region: "{{ aws_region }}"
        vpc_id: "{{ vpc_id }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      rules: 
        - cidr_ip: 0.0.0.0/0
          from_port: "22"
          proto: tcp
          to_port: "22"
    - name: "Create an ec2 instance"
      ec2:
        key_name: "{{ keypair }}"
        group: My Security Group
        image: "{{ ami }}"
        instance_type: "{{ instance_type}}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ public_subnet_id }}"
        assign_public_ip: true
        count: 1
        count_tag: 
          Name: Demo
        instance_tags: 
          Name: Demo    
        wait: true
      register: ec2
      
    - name: "Add new instances to host group"
      add_host: "hostname={{item.public_ip}} groupname=deploy"
      with_items: ec2.instances
      
    - name: "Wait for SSH to come up"
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection: 
        delay: 60
        state: started
        timeout: 320
      with_items: "{{ ec2.instances }}"
      
    - name: "Configure instance"
      hosts: deploy
      remote_user: root
      tasks: 
        - name: "Install Apache Web Server"
          yum: "pkg=httpd state=latest"
        - name: "start httpd"
          service: "name=httpd state=started"  
