apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: first-deploy
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd1
          image: httpd
          ports:
            - containerPort: 80
