apiVersion: v1
kind: ReplicationController
metadata:
  name: first-rc  
spec:
  replicas: 2 # replicas to launch
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:                 #containers scpecifications
      containers:
        - name: nginx      #container name
          image: nginx      # image to use
          ports:
            - containerPort: 80
